export const FETCH_NEIGHBOURS_SUCCESS = 'FETCH_NEIGHBOURS_SUCCESS';
export const FETCH_NEIGHBOURS_FAILURE = 'FETCH_NEIGHBOURS_FAILURE';

export const GET_CRITERIA_SUCCESS = 'GET_CRITERIA_SUCCESS';
export const GET_CRITERIA_FAILURE = 'GET_CRITERIA_FAILURE';

export const SELECT_CATEGORY_SUCCESS = 'SELECT_CATEGORY_SUCCESS';
export const SELECT_CATEGORY_FAILURE = 'SELECT_CATEGORY_FAILURE';

export const DESELECT_CATEGORY_SUCCESS = 'DESELECT_CATEGORY_SUCCESS';
export const DESELECT_CATEGORY_FAILURE = 'DESELECT_CATEGORY_FAILURE';

export const SET_PRICE_RANGE_SUCCESS = 'SET_PRICE_RANGE_SUCCESS';
export const SET_PRICE_RANGE_FAILURE = 'SET_PRICE_RANGE_FAILURE';

export const SET_MIN_SCORE_SUCCESS = 'SET_MIN_SCORE_SUCCESS';
export const SET_MIN_SCORE_FAILURE = 'SET_MIN_SCORE_FAILURE';

export const SET_MAX_DISTANCE_SUCCESS = 'SET_MAX_DISTANCE_SUCCESS';
export const SET_MAX_DISTANCE_FAILURE = 'SET_MAX_DISTANCE_FAILURE';
