export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_SALE_PRODUCT_SUCCESS = 'GET_SALE_PRODUCT_SUCCESS';
export const GET_SALE_PRODUCT_FAILURE = 'GET_SALE_PRODUCT_FAILURE';

export const GET_POPULAR_PRODUCT_SUCCESS = 'GET_POPULAR_PRODUCT_SUCCESS';
export const GET_POPULAR_PRODUCT_FAILURE = 'GET_POPULAR_PRODUCT_FAILURE';
