export const GET_FEATURED_ARTISTS_SUCCESS = 'GET_FEATURED_ARTISTS_SUCCESS';
export const GET_FEATURED_ARTISTS_FAILURE = 'GET_FEATURED_ARTISTS_FAILURE';

export const GET_ARTISTS_SUCCESS = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_FAILURE = 'GET_ARTISTS_FAILURE';

export const GET_SUGGESTED_ARTISTS_SUCCESS = 'GET_SUGGESTED_ARTISTS_SUCCESS';
export const GET_SUGGESTED_ARTISTS_FAILURE = 'GET_SUGGESTED_ARTISTS_FAILURE';

export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS';
export const GET_ARTIST_FAILURE = 'GET_ARTIST_FAILURE';

export const GET_ARTIST_PRODUCTS_SUCCESS = 'GET_ARTIST_PRODUCTS_SUCCESS';
export const GET_ARTIST_PRODUCTS_FAILURE = 'GET_ARTIST_PRODUCTS_FAILURE';
